FROM python:3.6

ADD PublisherApp.py /
ADD travixtest.json /
ADD PublisherConfigAirport-location.yaml /
ADD requirements.txt /
RUN pip install -r requirements.txt

CMD [ "python", "./PublisherApp.py", "PublisherConfigAirport-location.yaml"]