FROM python:3.6

ADD SubscribeIntoBigquery.py /
ADD travixtest.json /
ADD SubscriberConfigTrip-Detail.yaml /
ADD requirements.txt /
RUN pip install -r requirements.txt

CMD [ "python", "./SubscribeIntoBigquery.py", "SubscriberConfigTrip-Detail.yaml" ]