FROM python:3.6

ADD PublisherApp.py /
ADD travixtest.json /
ADD PublisherConfigFlight-Itinerary.yaml /
ADD requirements.txt /
RUN pip install -r requirements.txt

CMD [ "python", "./TransformData.py", "PublisherConfigFlight-Itinerary.yaml"]