FROM python:3.6

ADD SubscribeIntoBigquery.py /
ADD travixtest.json /
ADD SubscriberConfigFlight-Itinerary.yaml /
ADD requirements.txt /
RUN pip install -r requirements.txt

CMD [ "python", "./SubscribeIntoBigquery.py" ]